version: '3'

services:
  app:
    container_name: gpn_as_notify_receiver
    image: gpn_as_notify_receiver:v0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    command: python main.py
    env_file:
      - .env